import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Featured from "../components/Featured";
import BurguerList from "../components/BurguerList";
import AddButton from "../components/AddButton";
import styles from "../styles/Home.module.css";
import axios from "axios";

export default function Home({ burguerList, admin }) {
  const [close, setClose] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Restaurante de hamburguer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <BurguerList burguerList={burguerList} />
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }

  const res = await axios.get("http://localhost:3000/api/produtos");

  return {
    props: {
      burguerList: res.data,
      admin,
    },
  };
};
